# Don't use this file in production.

version: '3.8'

services: 
    database:
        image: postgres:13
        volumes: 
            - db_data:/var/lib/postgres/data
        environment: 
            POSTGRES_USER: tinyreader
            POSTGRES_PASSWORD: '12345'
            POSTGRES_DB: tinyreader
        ports:
            - '5432'

    app:
        build: .
        depends_on:
            - database
        environment: 
            DATABASE_URL: 'postgresql://tinyreader:12345@database:5432/tinyreader?serverVersion=13&charset=utf8'
        ports:
            - 9000:9000
        volumes: 
            - tr_build:/app

    server:
        image: nginx:1.21
        depends_on: 
            - app
        volumes:
            - tr_build:/var/www/tinyreader
            - ./server:/etc/nginx/conf.d
        ports: 
            - 8000:80
        expose: 
            - '8000'

volumes:
    db_data:
    tr_build:
